### ISSUE TITLE
Playlist

### ISSUE THREAD

**Issue by Webx123** [GoelBiju/pinybot#14]
is there anyway to turn off the playlist in the code? and have !yt play a youtube video and when u do !yt again it starts a diff video insted of adding it to the playlist?

**Comment by TechWhizZ199** [comment]
Thanks @Webx123 , I appreciate your feedback. Yes this is possible, this was in fact how the older versions worked, however due to the fact that people wanted an eaiser and managed way of playing videos/tracks.

On the contrary maybe I could implement a switch in order to turn this feature on?
If you have any other suggestions please feel free to comment.

**Comment by Technetium1** [comment]
If it is a function that not everyone would use, it would definitely be better as a toggled option.

**Comment by Autotonic** [comment]
Crude but until a proper commit is made to toggle:
https://github.com/TechWhizZ199/pinybot/blob/master/pinybot.py#L1726

replace that block with (or comment out):
```python
if _media is None:
     self.send_bot_msg(special_unicode['indicate'] + ' Could not find media: ' + search_str,
                                          self.is_client_mod)
else:
     self.last_played_media = _media
     self.send_media_broadcast_start(_media['type'], _media['video_id'])
     self.media_event_timer(_media['video_time'])
```

Should do it for now.

**Comment by Webx123** [comment]
hmm i tried to replace it with that and now when i open the .py file it opens and auto closes insted of runs xD i think im noob

**Comment by Autotonic** [comment]
As stated in the README you should be running from command line. This will keep the console open and allow you see any errors that have occured.
See: https://github.com/TechWhizZ199/pinybot/blob/master/README.md#run-the-bot

**Comment by Webx123** [comment]
ok it opens now and all and connects to your room but after you comment out and fix the block with the code you listed it and do !yt song name it does nothing.

**Comment by TechWhizZ199** [comment]
Just hold on for a bit, I'll place this into version 1.4.1 .

**Comment by GoelBiju** [comment]
This feature has been added in version 1.4.2, @Webx123 .

**Comment by Webx123** [comment]
Nicee How do you switch it?

**Comment by Technetium1** [comment]
@Webx123 [true or false](https://github.com/GoelBiju/pinybot/blob/master/config.ini#L47)

**Comment by GoelBiju** [comment]
@Webx123 there will be a command assigned to this very function called playlist_mode, which will toggle it from being Boolean True or False as @Technetium1 said. This should be released soon.
