### ISSUE TITLE
Time issues

### ISSUE THREAD

**Issue by TechWhizZ199** [GoelBiju/pinybot#23]
Issues with time commands e.g. specifically "!time New York" yields no results oddly from Google. Need to solve this.

**Comment by Technetium1** [comment]
Are you [SURE](http://puu.sh/pDIlP/2e13105233.png)?

**Comment by TechWhizZ199** [comment]
It's quite it wasn't working when I tried it. Please can you try it with v1.4.1 and tell me?

**Comment by Technetium1** [comment]
Absolutely sure it's [working](http://puu.sh/pHKPj/565293351c.png) now.

**Comment by TechWhizZ199** [comment]
Thanks @Technetium1 , I'll be sure to check it again, maybe it's an error on a patch. Also just to let you know, over the coming days I shall be starting to move content over to my official repository: HTTPS://github.com/GoelBiju since I think this repository just doesn't come to the standards required for  maintaining a codebase.

**Comment by Webx123** [comment]
anyway i can make the time in 12 hour format insted of 24? on my bot by changing a code withen the code?

**Comment by GoelBiju** [comment]
@Webx123 , I might consider adding AM/PM to the time since people want that, in case it displays in the 12 hour format. Though in all honesty, I think 24 hours should be a default.

**Comment by Webx123** [comment]
time should be 24 hr and time+ should be 12 hour. it should have both! so the users can decide which command to use.

**Comment by GoelBiju** [comment]
@Webx123 , ok sure, I'll see if I can add an AM/PM feature to time+, if not I'll see if the [time.is](http://time.is/) provides some AM/PM information on their response to our request.

**Comment by GoelBiju** [comment]
@Webx123 , just some further information. Time.is is now replying in 24 hour format which makes me think if is even neccessary to have a 12 hour format.

**Comment by Technetium1** [comment]
@GoelBiju Even if 24 hour is the standard all over, there are still people that have to go out of their way to convert it. I would very much like for both options to be there, or at the very least only the 12 hour time.

**Comment by Webx123** [comment]
THats the problem i as well as 90% of America and Canada unless we have family in the army or took the time to learn it has no clue how to figure out 24 hour time. We all go on 12 hour which is a big part of the bots following im sure i think there needs to be a 12 hour cammand AND a 24 hour command. !time can be the default 24 hour but there needs to be like the !time+ or something a 2nd command thats 12 hours so people can choose which time format they need/want.

**Comment by GoelBiju** [comment]
@Webx123 , this has now been added to the next versions. Thank for your help!
