### ISSUE TITLE
Tags for logs

### ISSUE THREAD

**Issue by Autotonic** [GoelBiju/pinybot#24]
Possibly an easier way to traverse logs. Adding tags like: 
(youtube) Autotonic started a youtube video
(bans) Autotonic was banned by pinybot

```cat blahblah_log.txt | grep (youtube) ````
Would show all lines with the tag "(youtube)"

**Comment by TechWhizZ199** [comment]
Sure @Autotonic , that's a notable point since I've personally found it tasking to read logs.

**Comment by GoelBiju** [comment]
I think this is something that @nortxort could possibily implement into the pinylib base.
