### ISSUE TITLE
wont run

### ISSUE THREAD

**Issue by Webx123** [GoelBiju/pinybot#25]
i tried to run it on my VPS windows server 2012 it said IMPORT ERROR: NO MODULE NAMED pyamf0 Any idea what im doing wrong? i installed all it said with C:\Python27\Scripts\pip2.exe install bs4 requests pysocks colorama pyamf and even manually tried to install pyamf again still get that error when i run pinybot.py

**Comment by Webx123** [comment]
Fixed it :)

**Comment by GoelBiju** [comment]
Hi @Webx123 ,
I am just curious to know what was the solution, in case it was an error in the program?
Maybe it can be improved if it was?
Thanks

**Comment by Webx123** [comment]
https://www.microsoft.com/en-us/download/confirmation.aspx?id=44266 i forgot to add that to my server haha totally my fault.

**Comment by GoelBiju** [comment]
@Webx123 . oh ok, yeah we require the compiler especially in the case of modules like PyAMF, at least I assume so.
