### ISSUE TITLE
autoban additions

### ISSUE THREAD

**Issue by Autotonic** [GoelBiju/pinybot#26]
!bn = X was added to bad nicknames
!ba = X was added to bad accounts

instead of "X was added to file" for both.

**Comment by Webx123** [comment]
i don't think this would be good because if a troll sees !bn his name then it says his name was added to bad nicks he will just come back under a new nick every time. But thats just my opinion :).

**Comment by GoelBiju** [comment]
@Autotonic , I see your point, messages returned should be relevant and not vague. @Webx123, you do have a point, though people make this choice, we cannot guarantee that it will happen all of the time, so I think we should stick to the message being relevant. If a ban was imposed quick enough, they will usually not see the message.

**Comment by GoelBiju** [comment]
This has been added to version 1.4.2.

**Comment by Webx123** [comment]
Ok no problem its prob just a Quick Edit in the .py file to change the wording anyway  if we wanted to change the response on our personal bot isnt it?

**Comment by GoelBiju** [comment]
Yes @Webx123 , It shouldn't be much of an issue if you wanted to change the wording, each command has it's own function, just view and change the function to what you need it to do.
