### ISSUE TITLE
Time on right

### ISSUE THREAD

**Issue by swiftSwathSee** [GoelBiju/pinybot#28]
Needs an option to move the clock to the right instead of the current left side.

**Comment by GoelBiju** [comment]
Hey @swiftSwathSee , nice to see you! Yeah I agree, the timestamps is something I have talked with nort about, we do need to increase the log and method of timestamping and also the way we display it in the console.

**Comment by GoelBiju** [comment]
@swiftSwathSee I have just tried this and without a proper curses console we can't really implement this. So I'm going to put this aside for now.

**Comment by swiftSwathSee** [comment]
Oh I meant directly to the right on the message, not aligned to the right edge:  
![sss](http://i.imgur.com/H5j6Zbv.png)

**Comment by GoelBiju** [comment]
@swiftSwathSee , I see what you mean now, sorry. I will place this in! Thank you Swift and I see you were on the same channel.
