### ISSUE TITLE
Toggle notifications display

### ISSUE THREAD

**Issue by swiftSwathSee** [GoelBiju/pinybot#29]
Notifications like leave/joins should be optional, like in the Tinychat.com client. Preferably toggled via commands in addition to the config file.

**Comment by GoelBiju** [comment]
I agree, there does seem to be a lot of information written into the console. In the case that someone doesn't want it, it should be an option.

**Comment by GoelBiju** [comment]
@swiftSwathSee , I have set this as a command directly in the console ('/notifications') and the option "join_quit_notifications" is available in the configuration file.
