### ISSUE TITLE
Separate nick and message colors

### ISSUE THREAD

**Issue by swiftSwathSee** [GoelBiju/pinybot#30]
Option to make the nicks a different color than their messages. Also, the colon after the nick should have a space.

**Comment by GoelBiju** [comment]
This could well be something we can state in the configuration file. I.e. nick_color = blue which can translate to the correct colorama style.

**Comment by GoelBiju** [comment]
@swiftSwathSee , with regards to the colon after the nick, did you mean when a message from a user is printed, there should be a space inbetween the colon and message?

**Comment by Technetium1** [comment]
`[02:29:03] UserName:hey`

vs

`[02:29:03] UserName: hey`
@GoelBiju

**Comment by GoelBiju** [comment]
Thanks @Technetium1 , I will change this.

**Comment by GoelBiju** [comment]
@swiftSwathSee , this was added however I feel like this gets really convoluted at times, so I have disabled it for now.

**Comment by GoelBiju** [comment]
This is not going to be in the next version for now, as it seems to complicate the console write function in pinylib quite a lot. However, if we were to build a GUI for the application in the future, this could be a feature worth adding.
