### ISSUE TITLE
auto_url

### ISSUE THREAD

**Issue by Autotonic** [GoelBiju/pinybot#31]
No HTTPS support.

**Comment by GoelBiju** [comment]
@Autotonic , this shouldn't be an issue, since HTTPS URLs seem to be working fine for me.

**Comment by Autotonic** [comment]
I'll have to look more into it. It seemed like only HTTPS URLs but it may be some more decoding/encoding nonsense. Close for now.

**Comment by GoelBiju** [comment]
Sure no problem @Autotonic .
