### ISSUE TITLE
Youtube ID search accuracy

### ISSUE THREAD

**Issue by Autotonic** [GoelBiju/pinybot#35]
We shouldn't be sending an entire URL to the Youtube Data API, this is leading to quite a bit of inaccuracy.
Should be using `youtube.youtube_time()` to get the time after splitting the ID from the URL.

**Comment by GoelBiju** [comment]
@Autotonic , I agree, this is something should be considered for both pinybot and @nortxort should consider changing this as well to a format of regex extraction or something similar (which Aida did illustrate to me) for tinybot.

[Line](https://github.com/GoelBiju/pinybot/blob/master/pinybot.py#L1877) to reference in pinybot and the [line (https://github.com/nortxort/tinybot/blob/master/tinybot.py#L1201) to reference in tinybot linked.
