### ISSUE TITLE
Removing Media Broken

### ISSUE THREAD

**Issue by Technetium1** [GoelBiju/pinybot#36]
The rm command seems to be entirely broken, it also references `!del`. https://github.com/GoelBiju/pinybot/blob/master/pinybot.py#L2237

**Comment by nortxort** [comment]
Hmm. Are you sure your not mixing up the files? as far as i know pinybot has always used !rm as command to remove tracks with. Ive just updated tinybot and media manager to enable deletions of tracks again.

**Comment by Autotonic** [comment]
its not broken just 1 off. Mostly likely fixed in the next revision. For now you can change 
https://github.com/GoelBiju/pinybot/blob/master/pinybot.py#L1891
to:
`' at #' + str(len(self.playlist) - 1) + '*', self.is_client_mod)`
This will print the correct playlist ordering when using `!rm`

**Comment by Technetium1** [comment]
Thanks @Autotonic! @nortxort the [usage](https://github.com/GoelBiju/pinybot/blob/master/pinybot.py#L2242) says 'del'.

**Comment by nortxort** [comment]
@Technetium1 Ah, i see what you mean now. I guess he forgot to change the usage to rm.
