### ISSUE TITLE
A custom list of users to use !bn command (etc.)

### ISSUE THREAD

**Issue by Webx123** [GoelBiju/pinybot#39]
Can i make it where only certain usernames can use the BN command? and if so how.

**Comment by Autotonic** [comment]
Take a look at how the botter or op functions work. 
https://github.com/GoelBiju/pinybot/blob/master/pinybot.py#L121
So you have your list of botters here. Can add another list with something like:
`badnick_privs = ['username1', 'username2', ]`


Now take a look at the function itself for the BN command
https://github.com/GoelBiju/pinybot/blob/master/pinybot.py#L1360

`if self.user_obj.is_owner or self.user_obj.is_super or self.user_obj.is_mod or self.user_obj.has_power:`

First lets remove everyone but say, the room owner:
`if self.user_obj.is_owner `
Now we can add our list to it
`if self.user_obj.is_owner or self.user_obj.user_account in self.badnick_privs:`

So self.user_obj.user_account is the account that sent the message, `in self.badnick_privs` checks if the account is in our list.

###Untested but should work

**Comment by Webx123** [comment]
so in files i need to add badnickusers txt file?

**Comment by Autotonic** [comment]
Nah you dont need it. You can just edit pinybot.py. 
Those edits were for account names, I made the mistake of using "username1". 
See: `self.user_obj.user_account`

**Comment by Webx123** [comment]
Worked nice anyway to add a message now to everyone else? ECT : You aren't on the access list for this command ?

**Comment by GoelBiju** [comment]
@Webx123 , what do you mean by everyone else? Do you mean if the people who are not on the list try to use the command, then reply saying "you aren't on the access list for this command"?

If so, just add to the existing format which @Autotonic stated, i.e.:

```python
if self.user_obj.is_owner or self.user_obj.user_account in self.badnick_privs:
    [THE CODE FOR THE !BN COMMAND HERE]

else:  <---- 1
    self.send_bot_msg('You are not on the access list for this command.', self.is_client_mod)

```
1. Place an else statement condition if the if statement is not satisfied.

2. You can use the send_bot_msg function to send a message to the room saying that that           person can't use the command.

**Comment by Webx123** [comment]
im so confused xD do i add both them codes or just  1 or the other?

**Comment by GoelBiju** [comment]
@Webx123 , well what did you mean initially when you said you wanted to add a message?

**Comment by Webx123** [comment]
like if there on the list to use the Bn command i want it to still say Added to file and work like normal but if there not on the list i want it to say you are not on the access list for this command. and not work.

**Comment by GoelBiju** [comment]
Yes that should just work fine, just add the else and the self.send_bot_msg after the else with the correct indentation.

**Comment by Webx123** [comment]
hmm it seems to break the .py file when i add it

**Comment by GoelBiju** [comment]
Please can you post your code, with a screenshot of supporting information?

**Comment by Autotonic** [comment]
@Webx123 

```
    def do_bad_nick(self, bad_nick):
        """
        Adds a bad username to the bad nicks file.
        :param bad_nick: str the bad nick to write to file.
        """
        if self.user_obj.is_owner or self.user_obj.user_account in self.badnick_privs::
            if self.is_client_mod:
                if len(bad_nick) is 0:
                    self.send_bot_msg(special_unicode['indicate'] + ' Missing nickname.', self.is_client_mod)
                else:
                    badnicks = pinylib.fh.file_reader(CONFIG['path'], CONFIG['badnicks'])
                    if badnicks is None:
                        pinylib.fh.file_writer(CONFIG['path'], CONFIG['badnicks'], bad_nick)
                    else:
                        if bad_nick in badnicks:
                            self.send_bot_msg(bad_nick + ' is already in list.', self.is_client_mod)
                        else:
                            pinylib.fh.file_writer(CONFIG['path'], CONFIG['badnicks'], bad_nick)
                            self.send_bot_msg('*' + bad_nick + '* was added to file.', self.is_client_mod)
                            if bad_nick in self.room_users.keys():
                                bn_user = self.find_user_info(bad_nick)
                                self.send_ban_msg(bn_user.nick, bn_user.id)
        else:
            self.send_bot_msg(self.usr_obj.nick + ' does not have the privileges to do this', self.is_client_mod)
```
    

That last `else`

**Comment by Webx123** [comment]
Omg worked! thanksss :D

**Comment by GoelBiju** [comment]
> if they're not on the list
If the user is not on the list already, the code plainly adds the nickname to the list. 
So, the lines which say:
```python
if badnicks is None:
    pinylib.fh.file_writer(CONFIG['path'], CONFIG['badnicks'], bad_nick)
```
Meaning that the nickname is added, however after that the function is finished and continues to wherever it was called from. There is no message in the function which says that it has been added, maybe there should be(?) @nortxort should add this to tinybot as well if that is the case.

**Comment by Webx123** [comment]
no that part works. Like if there on the list it says Added to file and works but if there not on the list it still says nothing. insted of the error code does not have the privileges to do this that we added. the Message to those not on the list is whats not working ... it works great for those who are added to the list.

**Comment by GoelBiju** [comment]
@Webx123 , it works, though it just doesn't reply with any information as to whether the nickname was added to the list or not. We can just put some information into that function in the next update. 

Thank you!

**Comment by Webx123** [comment]
thats not the issue tho all that works lol i think we are on 2 different pages lol

**Comment by Webx123** [comment]
ok lets say i add a username to the allowed list to use the !bn command they do !bn name it then says Name added to file (like it suppose to works great) but for them who are not on the allowed list to use the !bn name they do !bn name it says nothing (so it dont add the name to file which is what it suppose to do that is great ) all im trying to add now is for those who i do not add to the list allowed to use !bn command i want it to insted of saying nothing it say "YOU ARE NOT ALLOWED TO USE THIS COMMAND" so they know why its not working when they try to do !bn insted of saying nothing at all because there not all the allow list. if that makes sense ( i know i can be confusing sometime lol)

**Comment by nortxort** [comment]
@Webx123 It would probably be easier to help if you made a [gist](https://gist.github.com/) and posted your pinybot.py file so people can see the changes you've made so far.

**Comment by GoelBiju** [comment]
@Webx123 , like @nortxort , please post your code and it should work since there is an else statement followed by the send_bot_msg function. Please post the code you have right now, then we can see what needs to be adjusted.

**Comment by GoelBiju** [comment]
I am closing this as there seems to be no further activity taking place.
