### ISSUE TITLE
Catching cloned/similar nicknames in a room

### ISSUE THREAD

**Issue by GoelBiju** [GoelBiju/pinybot#41]
Algorithm to match cloned nicknames in a room and report it back.

Thank to @notnola for this suggestion.

Rough outline of how it should work.
1. Room object on a new user,
2. Possible clones of nicknames saved as an attribute in the object
3. Alert room of a the possible cloned nickname if the existing nickname is the room and the clone sets to a nickname in the cloned nicknames attribute.

**EDIT**: This could be a separate module which can then be an addon to the bot.

**Comment by Autotonic** [comment]
if clone's account is not original owners account

**Comment by GoelBiju** [comment]
@Autotonic , I'm not sure that would matter since we can only login with one account.

**Comment by GoelBiju** [comment]
This might not get implemented at the moment.
