### ISSUE TITLE
echo owner_msg as undercover to mobile users

### ISSUE THREAD

**Issue by Autotonic** [GoelBiju/pinybot#43]
Since mobiles cannot see owner messages.

**Comment by GoelBiju** [comment]
@Autotonic , this is a good point. The website itself should implement this into their app themselves, though in the meantime we could change it to send an undercover message. 

There are only two issues with this, there are a lot of references to owner_run_msg in the source code, so changing this is not easy. If we were to change this at the root, in the owner_run_msg function in pinylib, one issue would be that we would not know if the user was logging in from a mobile or not.

**Comment by GoelBiju** [comment]
At this point, we cannot be sure if the user is on a mobile device or not, so we cannot really do this @Autotonic .
