### ISSUE TITLE
Reducing large repository size

### ISSUE THREAD

**Issue by Autotonic** [GoelBiju/pinybot#44]
This is why:

```
aida@blueberry ~/P/pinybot> du -h .git
8.0K    .git/info
44K .git/hooks
8.0K    .git/logs/refs/heads
8.0K    .git/logs/refs/remotes/origin
12K .git/logs/refs/remotes
24K .git/logs/refs
32K .git/logs
8.0K    .git/refs/heads
8.0K    .git/refs/remotes/origin
12K .git/refs/remotes
4.0K    .git/refs/tags
28K .git/refs
4.0K    .git/branches
4.0K    .git/objects/info
34M .git/objects/pack
34M .git/objects
34M .git
```

.git/objects is HUGE!

**Comment by GoelBiju** [comment]
I was just reading an article regarding [reducing the repository size](http://stackoverflow.com/questions/2116778/reduce-git-repository-size). This would include reducing the .git size. However from what I have read, it looks as if the objects folder is imperative to how git works, in fact all of those files are, we can prune the process when we push the files, however just removing it will be dangerous for the repository.

**Comment by Autotonic** [comment]
This is related to the ffmpeg binary in the pinybotAlpha branch

**Comment by GoelBiju** [comment]
I was just cloning the master branch on pinybot and realised how the process resulted in downloading 64.78mb of objects from the remote repository. I believe that I need to compress this size down into something managable.

**Comment by GoelBiju** [comment]
@Autotonic , has removed a lot of the data from the pinybot-dev branch in commit: b3ee50f46c6a8a9fa43066ba5ad92768643fca73
