### ISSUE TITLE
Autopm

### ISSUE THREAD

**Issue by justsmoke420** [GoelBiju/pinybot#47]
When I try to set autopm in the room it tells me " There is no PM message set in the configuraton." What exactly am I doing wrong or how do I "set the configuration? " Thank you for your time.

**Comment by GoelBiju** [comment]
@justsmoke420 , thanks for posting your query.

Setting the configuration means you just need to enter the private message string in the configuration field in your [config.ini](https://github.com/GoelBiju/pinybot/blob/master/config.ini#L61). Make sure you set the auto_pm to True above it (it seems like you already did), if you have any other issues please be sure to ask! :smiley:

**Comment by justsmoke420** [comment]
Problem solved!

**Comment by GoelBiju** [comment]
@justsmoke420 , great work!
