### ISSUE TITLE
pinybot-gui

### ISSUE THREAD

**Issue by GoelBiju** [GoelBiju/pinybot#48]
@swiftSwathSee mentioned to me about developing a basic GUI interface for the script, alongside this command line/terminal version.

This could be something worth looking into with a proper framework (the likes of PyQt).

**Comment by GoelBiju** [comment]
There is a [repository](https://github.com/GoelBiju/pinybot-gui/) dedicated to this in place if this is to be developed.

**Comment by GoelBiju** [comment]
I have begun to post the UI design files generated from the PyQt Designer on the repository.

**Comment by swiftSwathSee** [comment]
I haven't forgotten about this. Definitely add the simple (working) basics and I'll get started right away on adding the rest.

**Comment by GoelBiju** [comment]
Thank for the support @swiftSwathSee , firstly you might need to get the PyQt4 environment setup for Python 2.7. You can download the all-in-one binary installer [here](http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.11.4/PyQt4-4.11.4-gpl-Py2.7-Qt4.8.7-x32.exe). This should install all the necessary tools required to edit UI files (Qt Designer).
