### ISSUE TITLE
error running the bot

### ISSUE THREAD

**Issue by zootshecfur** [GoelBiju/pinybot#53]
i got stuck on this when i load the bot now

http://imgur.com/a/It8qY

**Comment by GoelBiju** [comment]
Hi @zootshecfur , the issue looks like an request to get the room information for the bot to connect doesn't seem to be received on your end. I can't really be sure as to what is happening by completely looking at it, but it could be possibly because of your internet connection.

**Comment by TheHomelessMan** [comment]
Had the same error.

what I did was add these 2 lines after the imports in pinybot.py

reload(sys)
sys.setdefaultencoding('utf8')

**Comment by GoelBiju** [comment]
What do you think the error was @TheHomelessMan ?

**Comment by TheHomelessMan** [comment]
Basically the problem is that you're trying to print a unicode character, but your terminal doesn't support it.

Well, that's what I'm assuming.
so either those 2 lines or update language packages on your PC.

**Comment by GoelBiju** [comment]
I think @zootshecfur , managed to fix this.
