### ISSUE TITLE
Path issues with Linux

### ISSUE THREAD

**Issue by Autotonic** [GoelBiju/pinybot#54]
Couple of errors. Will look into it more when I have time.

**Comment by GoelBiju** [comment]
@Autotonic , sure thank you very much.

**Comment by GoelBiju** [comment]
I'm not sure if the beta version of pinybot should fix the issue you are having, but [this line](https://github.com/GoelBiju/pinybot/blob/pinybot-beta/pinybot.py#L67) was added to replace the previous path in the configuration file when I was trying to setup the bot on OpenShift which also ran on Linux.

**Comment by GoelBiju** [comment]
This might not be an issue in the new version, if it does become an issue please do say @Autotonic .

**Comment by GoelBiju** [comment]
I will close this for now @Autotonic , if it is still an issue please do say. Thank you!
