### ISSUE TITLE
Stopped logging in

### ISSUE THREAD

**Issue by triggertrey** [GoelBiju/pinybot#62]
Hi I need  LIL help I reset my bot after tc did a update changing the login page which I changed the url on the web request but it still fail to login 

url was changed from /login  to /start?#login

**Comment by NawtJ0sh** [comment]
Looks like tc changed the login again.

**Comment by Autotonic** [comment]
Lol I cant even sign out.

**Comment by triggertrey** [comment]
i had to clear cookies to sign out  i tried changing links to the new url but it wont post

**Comment by CrookedTech** [comment]
Cant even sign in 
in any way keeps asking for recaptcha
and then reconnects

**Comment by CrookedTech** [comment]
looks like tinychat changed the login zone

**Comment by rucutdude89** [comment]
Anybody figure this out yet ?

**Comment by Autotonic** [comment]
@rucutdude89 I'll fix it if I get time at work or when I get off, assuming someone else doesn't. So roughly in 7 hours time.

**Comment by rucutdude89** [comment]
Cool, Have any idea where to start? You think its an easy fix?

**Comment by CrookedTech** [comment]
i think it might be easy, i noticed they added some type of _token in the login data it might be require,
all i did noticed is  they removed the ids  from the form login and left the names as login_username and login_parrword and something extra which is a _token and the link 
https://tinychat.com/login#signin i might not be right  on this, but i think is the new token thing they added i dont know if it was already in the form before i dont remember seeing it in the login structure.

**Comment by ItzEvan** [comment]
Where and How do we add that. I'm waiting patiently xD but would love to Try and fix on my own just don't know where to start.

**Comment by CrookedTech** [comment]
@ItzEvan i think it needs to be added in that function
https://github.com/GoelBiju/pinybot/blob/master/api/web_request.py#L134

but what i dont know is if that token changes every time or  if it needs to make a function to auto generate that token.

**Comment by CrookedTech** [comment]
@ItzEvan  right here: https://github.com/GoelBiju/pinybot/blob/master/api/web_request.py#L134

but all that needs to be rearranged asome  parameters needs be removed.

just like the data in the image i sent earlier
https://s10.postimg.org/f5v8xy9ih/login.png

thats the post method.

**Comment by ItzEvan** [comment]
@CrookedTech thanks for that I changed login url but also 

Am I getting this error because of the login change or do I have something configured wrong?



![8eec3528843c6cf5abc2c12fa37123e5](https://cloud.githubusercontent.com/assets/25851358/23080549/27136b80-f51f-11e6-89fa-ddbe90890349.png)

**Comment by CrookedTech** [comment]
@ItzEvan no that way is not gonna work dont know  exactly how  to add it.
but i will just wait till goelbiju figured it out on how to apply it because i think it needs a function for that.

**Comment by ItzEvan** [comment]
Ok but yeah is the login change mst likely the reason why I am getting that error?

@CrookedTech

**Comment by CrookedTech** [comment]
@ItzEvan yeah also need to change the login variables for the post method and adding the _token too
for some reason in the  tinychat embed links it doesnt let me join the room if im logged in
but whenever im logged out i will join normally so must be it and something else.

**Comment by nortxort** [comment]
@ItzEvan It looks like your using a older version of python and that most likely the reason why you are getting SSL errors. could you check your python version? If that is the case, you might wanna have a look at [this](http://stackoverflow.com/questions/29134512/insecureplatformwarning-a-true-sslcontext-object-is-not-available-this-prevent)

As for the login fix, you need to parse the _token from the page before making the login post and of course change the post data to match that of the new way.

**Comment by ItzEvan** [comment]
Ok I am using 2.7 that is probably why, but I have no Idea how to fix the rest on me own so I will be waiting for someone to save the day.

**Comment by nortxort** [comment]
@ItzEvan what does the first line in C:\Python27\README.txt read?

**Comment by Autotonic** [comment]
@ItzEvan https://github.com/GoelBiju/pinybot/issues/59  are you running from a server? If so what Distro/OS

**Comment by ItzEvan** [comment]
No from pc 

Just trying to get it runny myself has it been updated or am I gonna have to re arrange settings myself?

**Comment by Webx123** [comment]
anyone found a fix for this yet? mine still says LOGIN NOT FOUND

**Comment by Autotonic** [comment]
@Webx123 The pull request @CrookedTech made looks like works. If not, look at pinylib/tinybot from @nortxort repo

**Comment by Webx123** [comment]
idk where to add _token at

**Comment by Webx123** [comment]
lol ive tried everything is there going to be a updated py in the repo soon?

**Comment by ItzEvan** [comment]
@Autotonic I got it connected and everything but commands dont work.

**Comment by Webx123** [comment]
all the tips i see seem to be for the beta Version what about to real version :S

**Comment by ItzEvan** [comment]
Yeah bot is working 8 ball and everythin just not botter but it says No handlers could be found for logger/ pinylib

I will be in debt to anyone who helps me get this working.

**Comment by zootshecfur** [comment]
anyone got the bot to work with out beta? to login ? cause i can get it to work with out a login and every thign that was posted to fix it is for the beta and i cant seem to get the beta to open

**Comment by Webx123** [comment]
im starting to thank you cant. and the beta version dont even work it logs in but it has no commands that work besides 8ball lol and no easy access to banned names,accounts

**Comment by GoelBiju** [comment]
Sorry for the delay, I will try to get this fixed soon. I suggest using [tinybot](https://www.github.com/nortxort/tinybot/) for now.

**Comment by Webx123** [comment]
tinybot auto closes

**Comment by GoelBiju** [comment]
You may have to use the bot_client.py file to run it @web123 instead.

**Comment by Webx123** [comment]
thanks @GoelBiju that beta version is awful. I will just wait on the Real version thanks :)

**Comment by GoelBiju** [comment]
Logging in should have now been fixed.

**Comment by Webx123** [comment]
on the main old version :O :D??????!!!

**Comment by GoelBiju** [comment]
I plan to commit the beta straight into the main version (final update), so this will should fix everything so far.
