### ISSUE TITLE
Connected to room with mod account but commands arent working

### ISSUE THREAD

**Issue by ItzEvan** [GoelBiju/pinybot#64]
I am connected to the tc room through the bot I can send chat messages to the tc room through bot but I cant bot people or play youtubes

**Comment by Webx123** [comment]
how did you fix the login issue? my bot still cant login

**Comment by ItzEvan** [comment]
How do you get commands to work once connected through the bot lol info witch?

**Comment by Webx123** [comment]
ohh im not sure my bot still says Not Logged in. when  i try to connect it every since tc changed login pages my bots been broke

**Comment by zootshecfur** [comment]
u can still get ur bot in but with out a login account 
im still trying to figure out for the non beta bot

**Comment by CrookedTech** [comment]
@ItzEvan  well if you are using the beta version in order to use the commands first sent a private message to the bot then type !opme light
after that you are a botter controller but if you want to enable public commands
after making your self a bot controller type in the chatbox !pub
and there others will be able to use yt commands.

i dont know if thats what you want.

and make sure you redownload the beta version from the pull request the prevous one was uploaded  wrong.

**Comment by ItzEvan** [comment]
@CrookedTech I did so I am using your pinybot repository but it keeps failing to login.

**Comment by ItzEvan** [comment]
and getting this error

![c4575f802985c5666abc95a2ae04bd86](https://cloud.githubusercontent.com/assets/25851358/23099472/0f79c664-f636-11e6-8225-4d0c4208c8d2.png)

**Comment by zootshecfur** [comment]
we want the non beta to work lol

**Comment by Webx123** [comment]
@zootshecfur Yess!!! the beta dont do half what the real version can do and i cant even get beta to run half the time much less do commands xD

**Comment by CrookedTech** [comment]
@ItzEvan actually the beta version does everything the main version does

but make sure you download it from here: https://github.com/CrookedTech/pinybot/tree/pinybot-beta
 it runs fine with me
it should work with no problem
and make sure you run the bot_client.py  file

@Webx123 and for the real version have to wait till
it gets updated.

**Comment by Webx123** [comment]
beta version lets everyone and there brother play youtube not just mods..

**Comment by Autotonic** [comment]
@Webx123 https://github.com/GoelBiju/pinybot/blob/pinybot-beta/pinybot.py#L982
and
https://github.com/GoelBiju/pinybot/blob/pinybot-beta/pinybot.py#L600

`!pub`

**Comment by ItzEvan** [comment]
@CrookedTech I am still always getting login fail but can connect as guest fine. 

Do you have any Idea what is wrong and I have made a fresh account and saved exact info yes ha .

Or anyone It just keep says login failed.

**Comment by CrookedTech** [comment]
no idea, but i migt help you through teamviewer
i dont really know whats causing that, it shouldnt say login failed unless you are using the main repo
the only version  fixed for now is the beta version.

**Comment by ItzEvan** [comment]
I am using the repository off your page @CrookedTech are you available though teamview.

**Comment by CrookedTech** [comment]
@ItzEvan  yeah sure give me  tinychat room and there you will give me your teamviewer login.

**Comment by ItzEvan** [comment]
thedanklaration

**Comment by GoelBiju** [comment]
This should be now working.
