### ISSUE TITLE
Hey Bot is working great Thanks to crookedTech but Anyone is able to op themselves without key and usernames are case sensitive.

### ISSUE THREAD

**Issue by ItzEvan** [GoelBiju/pinybot#66]
Bot works and logins in makes bans and everything perfect but after resetting secret key before using fresh bot someone was able to op themselves without key and also the user names are case sensitive so when you go to add someone to bans or to op them it has to be exactly type where as other versions weren't this way.

**Comment by CrookedTech** [comment]
@ItzEvan No, no one can op anyone  unless you are a botter and  keep in mind that mods  can use almost every commands  since they are mod so dont be surprise about it

**Comment by senthome** [comment]
I'm still having the same login issues even after installing a fresh install from CrookedTech. Am I doing something wrong?

**Comment by CrookedTech** [comment]
@senthome thats because you are installing the main version in my fork repo
you need to install it from here: https://github.com/CrookedTech/pinybot/tree/pinybot-beta

**Comment by senthome** [comment]
oh gr8 thank installed the beta its stuck at this point 

"Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]"

**Comment by senthome** [comment]
sorry for the noob questions lol

**Comment by justsmoke420** [comment]
Hey Crook,

I seem to be having some trouble using some L1 commands. I currently use the owner's account for the bot. Even while using the Super Key it seems that some commands don't function. Ex: !gr, !crb, etc. Maybe I'm doing something wrong or they simply don't work currently? 
Thanks.

**Comment by CrookedTech** [comment]
@justsmoke420 well that kind of commands  such as  !gr it requires the bot has the owner account otherwise is not gonna work. what it does it enables the greenroom from the panel settings.

**Comment by justsmoke420** [comment]
@CrookedTech I do currently use the bot with the owner account.

**Comment by CrookedTech** [comment]
@justsmoke420 ok try this  sent the bot a pm and  type !opme nergy
and then use the command  in the room.
should wok that way.

**Comment by justsmoke420** [comment]
@CrookedTech I seem to have figured it our and have no idea what I did wrong in the first place..... my mistake! One last question.... When I do enable the greenroom it activates the rooms password for broadcasting including mods. Is there a standard password or is there a way of changing it without actually going into my privacy settings on Tinychat? 
Thank you for all of the assistance,

**Comment by CrookedTech** [comment]
@justsmoke420  no it actives the awaiting approval for normal users, mods can broadcast without approval
thats  all
look
!mod to mod an account in the panel settings.
!rmod to remove mod account from the panel settings list
!p2t  to enable and disable push2talk
!gr to enable and disable greenroom
!crb to clear all bans

thats  the owner commands so far.

**Comment by senthome** [comment]
@ CrookedTech still stuck at this point, any help would be gr8tly appreciated. 

Exit status: 0
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by ItzEvan** [comment]
Could you add the option to mute people

**Comment by ItzEvan** [comment]
@CrookedTech

**Comment by CrookedTech** [comment]
@ItzEvan it already has it use
!mute

**Comment by justsmoke420** [comment]
@CrookedTech Do you have any issue's getting the Private Greet PM function to work?

**Comment by CrookedTech** [comment]
@justsmoke420 Nope , looks like it needs to get fixed.

**Comment by ItzEvan** [comment]
That option to mute does work. says it does but it doesnt.

**Comment by zootshecfur** [comment]
sorry did not want to make a new tread but the !syncme !stopme for youtube or souncloud option dosnt seem to work in the beta also theres no !camblock

**Comment by rizzlemedizzle** [comment]
@CrookedTech Myself and another guy are having the same issue with the beta. Error we get is:

Enter room name: stoneychatvid
Enter nickname (optional): bot
Login? [enter=No] no
Account: rizzlemedizzle
Password: nolan85
[16:15:12] Logged in as: rizzlemedizzle
[16:15:13] Connect parameters set. Connecting...
No handlers could be found for logger "pinylib"
[16:15:13] ============ RECONNECTING IN 60 SECONDS ============
[16:16:13] Login okay.
[16:16:14] ============ RECONNECTING IN 120 SECONDS ============
[16:18:14] Login okay.
[16:18:16] ============ RECONNECTING IN 240 SECONDS ============
[16:22:16] Login okay.
[16:22:17] ============ RECONNECTING IN 480 SECONDS ============


Any ideas?
Thanks!

**Comment by Autotonic** [comment]
@rizzlemedizzle What OS?

**Comment by rizzlemedizzle** [comment]
I'm running Ubuntu but happening on Mac OS too

**Comment by Autotonic** [comment]
@rizzlemedizzle see #69 
Change https://github.com/GoelBiju/pinybot/blob/pinybot-beta/pinylib.py#L177 and https://github.com/GoelBiju/pinybot/blob/pinybot-beta/pinylib.py#L219 to `False` and give it a shot.

**Comment by rizzlemedizzle** [comment]
thank you mate!

**Comment by senthome** [comment]
Works on Mac now thanks @Autotonic !!!

**Comment by Autotonic** [comment]
@senthome Join the gitter [Here](https://gitter.im/pinybot/Lobby) or join #pinybot on freenode irc network.  freenode has some web interface, or whatever MacOS or if you can find some CLI client for it.

**Comment by rizzlemedizzle** [comment]
Weird... had it working. Now I get the same error.
 If I set the config file to True (to use log in details) I get a captcha followed by this error:

https://tinychat.com/cauth/recaptcha?token=42a385678464095ddaae1f85e3fa5a88f0ef334e
Solve the captcha and click enter to continue.
No handlers could be found for logger "pinylib"
[06:11:16] ============ RECONNECTING IN 60 SECONDS ============

and if i don't use the config file and input account ad password, and then get stuck in a loop of asking for username and password.

This is with pinylib.py set is_win=False

**Comment by Autotonic** [comment]
@rizzlemedizzle I recommend you join the Gitter ( https://gitter.im/pinybot/Lobby ) so we can resolve this issue outside of this already inflated thread.

**Comment by GoelBiju** [comment]
There should not be an issue with setting a bot controller and usernames are case-sensitive as they depend on what you enter in (since we can only handle lower username forms, I will make sure we can handle this).
