### ISSUE TITLE
Finalising

### ISSUE THREAD

**Issue by GoelBiju** [GoelBiju/pinybot#67]
I was planning on allowing more people to commit to the repository in order to make it more open source and friendly for everyone's ideas to be used. 

I would very much appreciate it if anyone can help contribute to it.

**Comment by Webx123** [comment]
can we get the main version working before a bunch of changes starts getting made tho? i love the main source its perfect how it is now if it would just login :( change is not always best the beta version is proof of that

**Comment by CrookedTech** [comment]
hey @GoelBiju so what are you planning on  the main version.
are you gonna update it?

**Comment by ItzEvan** [comment]
I think you need to make a gitter for this discussion.

**Comment by GoelBiju** [comment]
The main version will be updated by pushing the beta version into the main repository. @Webx123 , which parts of the beta did you want improved? Currently the main version is not going to be updated as it is on an older format, so the beta version will be improved to become stable @CrookedTech .

@ItzEvan , I have created a Gitter room for the repository here: https://gitter.im/pinybot/

**Comment by Webx123** [comment]
ohhh nooo!!!! it would be easier to tell you what is good about the beta bot. and thats it logs in other then that its such a downgrade and a mess. Anyone can do commands theres no youtube only for mods ... before mods can use commands they have to OP themself thats just un needed and dumb. Ontop of that theres no easy .txt files for ban names and banned accounts... the joke command is gone. the thing dont work half the time its set up is just way worse then the original its alot more cpu dependent on a server. its just not very good at all. i understand its free and i cant complain tho but is there anyone here i can pay to fix the main version. ill happily pay who ever can get it running.

**Comment by genba2** [comment]
the .txt files are still around, however they don't exist until an entry is entered. they'd be in your pinybot beta dir\rooms\[room name]\ iirc. youtube functionality is moot as google messed that up sidewide for tinychat. joke stuff would be easy to reimplement, cleverbot is in now which wasn't before. there's a lot more added to the beta version such as better user class. i can make mods/enhancements for certain things, however python isn't my native tongue. i can say the beta version is far superior in terms of being able to manage room entrants, particularly those not logged in. i'm not very familiar with git but i'd almost push my update to add the .nli [not logged in] property to the user class and related purge function. the gate function on my version is nearing 100% efficacy. my appreciation to those whom have put their time and effort into pinybot, as it makes tinychat a tolerable platform for me. i heard talk of a tiered mod system being worked on, i think that's another good idea to have in there.

**Comment by GoelBiju** [comment]
I will be pausing any production in the development of this repository for now. I will come back to this soon, however @Autotonic will be available to help out as (if he is available) to solve any issue you may have. 

Since everyone was requesting to fix the main version, I will make sure that get's fixed with the latest account files from the pinylib, but feel free to use other services.
