### ISSUE TITLE
passing unicode to the youtube search

### ISSUE THREAD

**Issue by Autotonic** [GoelBiju/pinybot#7]
pass characters properly to the youtube api.

example:  DΞΔN "bonnie & clyde"

**Comment by TechWhizZ199** [comment]
I will try and see if this can be implemented, but there could be restrictions regarding the way the search is actually sent. As in, maybe unicode characters are converted before it is sent via a URL.

**Comment by Autotonic** [comment]
In most cases the unicode characters can stripped and will return the same video. Which is what I doing. Don't sweat if you don't want to mess with it.

**Comment by TechWhizZ199** [comment]
Just simply try getting the Google YouTube API search URL and place in the Unicode as he search, see what comes up. As in whether a normal search is conducted or not, that will show us if we can just place in the unicode.

**Comment by TechWhizZ199** [comment]
Issue has been resolved by removing conversions to string in key functions in YouTube.py in the API folder.

**Comment by GoelBiju** [comment]
@Autotonic , this issue is actually still persistent. We cannot decode unicode with the console_write and we cannot encode any extensive unicode provided with the !yt command and then URL quoting it. It does work for i.e. percentage signs since that is "quote-able" though not for unicode.

**Comment by GoelBiju** [comment]
WIth regards to a direct search on YouTube for that particular video. The URL for the search (when copied from the unicode search to here as a comment) results in

```HTTP
https://www.youtube.com/results?search_query=D%CE%9E%CE%94N+%22bonnie+%26+clyde%22
```

**Comment by Autotonic** [comment]
Don't think that is necessary. I'd assume the Youtube Data API is handling the conversion. I haven't had any issues with queries that include unicode.

**Comment by GoelBiju** [comment]
@Autotonic , they maybe handling the searching though I am still not sure if we are sending things correctly. It would be best if we send it in the correct format from our side as opposed to the incorrect one.

**Comment by GoelBiju** [comment]
@nortxort has developed a brilliant solution to this issue in the new version of [tinybot](https://github.com/nortxort/tinybot/). As the new versions will be using tinybot from now on, I can close this.
