### ISSUE TITLE
Queuing multiple songs at once

### ISSUE THREAD

**Issue by Autotonic** [GoelBiju/pinybot#8]
`!yt song 1 | song 2 | song 3`
or..
`!yt song 1 && song 2 && song 3`

Not really useful for links because the message would be too long.

**Comment by TechWhizZ199** [comment]
This will be a useful feature, no doubt. Should be simple to put into effect.

**Comment by TechWhizZ199** [comment]
I have assigned this for later use.

**Comment by GoelBiju** [comment]
This has been added now @Autotonic .

**Comment by Technetium1** [comment]
@GoelBiju I feel like `|` is a better separator because of TinyChat's character limit, will it be easy to change?

**Comment by GoelBiju** [comment]
@Technetium1 , it's just a simple branch with and if statement in the do_play_media function. I can change it to ```|```, howevever I felt that people would easily find '&&' more easily than pressing shift and the backslash key.

**Comment by Autotonic** [comment]
`&&` makes more since in BASH `a && b` means `do a and once complete do b`. 
While `a | b` would mean `do a then pipe a to b`

**Comment by GoelBiju** [comment]
I agree with @Autotonic on this point, it is simpler to find and use and makes more sense when seen. I think I will keep it this way for now.
